### ISSUE TITLE
Discourse forum - upgrade docker image

### ISSUE THREAD

**Issue by brendam** [makehackvoid/makehackvoid.com#110]
We have some errors in the log files and the fix is on this page:
https://meta.discourse.org/t/periodically-failing-job-permission-denied-root-netrc/20079/4 which says to upgrade to latest discourse docker:

```
cd /var/discourse
git pull
./launcher rebuild app
```

**Comment by jamiereid** [comment]
This issue is no longer relevant (due to our discourse image having been rebuilt completely). It is now kept up to date much more frequently by @csirac2 and I.
