### ISSUE TITLE
Make the embedded map look nicer

### ISSUE THREAD

**Issue by cmrn** [makehackvoid/makehackvoid.com#93]
It would be good to either find a theme for the OSM map to make it look a bit nicer, or swap back to Google Maps. As it stands, it's a bit ugly.

**Comment by jamiereid** [comment]
Has the map disappeared from the website, or is it just a bug on my computer?

**Comment by brendam** [comment]
​I noticed last night that it was missing for me, meant to report it.

**Comment by jamiereid** [comment]
Fixed by PR #120
